/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Jerry' at '16-9-25 下午2:18' with Gradle 3.1
 *
 * @author Jerry, @date 16-9-25 下午2:18
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
